Panier:
    type: entity
    table: panier
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
        produitid:
            type: integer
            nullable: false
            options:
                unsigned: false
        quantite:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
